# Generated by Django 4.2.10 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='media/product/%Y/%m')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='media/services/%Y/%m')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Колличество')),
                ('product', models.ManyToManyField(blank=True, related_name='product', to='produce.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оказания услуг')),
                ('time_start', models.TimeField(auto_now_add=True, verbose_name='Удобное время оказания услуг с')),
                ('time_end', models.TimeField(auto_now_add=True, verbose_name='Удобное время оказания услуг по')),
                ('services', models.ManyToManyField(blank=True, related_name='services', to='produce.services', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказы услуг',
                'verbose_name_plural': 'Заказы услуг',
            },
        ),
    ]
