# Generated by Django 4.2.10 on 2024-05-16 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produce', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ProductItem',
        ),
        migrations.AddField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='produce.order', verbose_name='Тендер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='produce.product', verbose_name='Продукты'),
        ),
    ]
