# Generated by Django 4.2.10 on 2024-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_remove_order_productitem_productitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Контактный телефон'),
        ),
    ]
