# Generated by Django 4.2.10 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product/%Y/%m'),
        ),
    ]
