# Generated by Django 4.2.10 on 2024-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оформления заказа'),
        ),
    ]
