# Generated by Django 4.2.10 on 2024-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0006_alter_orderservices_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservices',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата оказания услуг'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='time_end',
            field=models.TimeField(null=True, verbose_name='Удобное время оказания услуг по'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='Удобное время оказания услуг с'),
        ),
    ]
